src/Core/EFieldSolver.cpp

'rlog' vector in EFieldSolver.cpp (83) is not resized when  shortRange method is called. 
This result in an undefined behaviour when accessing rlog.
This patch correct such an issue.

corrected bug in EFieldSolver.cpp (rlog not resized)

---

src/Core/BeamSolver.cpp

In https://github.com/svenreiche/Genesis-1.3-Version4/blob/master/src/Core/BeamSolver.cpp#L68-L81
rpart is updated every time the evaluated particle is found to be on the grid. 
If the particle is not on the grid, it takes the values of the rpart elements set by the previous particle which, I think, it's an error. Am I wrong?    
Also for me, it's unclear if out-of-grid particles still need to be simulated at all or not.

put rpart = 0 for out of the grid particles

---

src/Core/Beam.cpp

Dear Sven,
I've found a bug in the harmonic up-conversion code of GENESIS4. The vertical optics got screwed up.
This should fix the issue.
Best
Christoph

fixed bug in harmonic upconversion screwing up vertical beam optics

---

build_info.sh

The script is not posix shell compatible, but uses bash only syntax, thought the shebang requested only sh.

Fix wrong shebang in build_info.sh

---

Makefile
include/Beam.h
include/HDF5base.h
include/Setup.h
src/Core/Beam.cpp
src/IO/HDF5base.cpp
src/IO/Output.cpp
src/Main/GenMain.cpp
src/Main/Setup.cpp
src/Main/Track.cpp

Two new features:
1) Write evolution of particle distribution to .out.h5: In one4one simulations, generate additional dataset  "/Beam/npart_in_slice" in .out.h5 file, containing for every integration step the number of particles per slice. This data describes the evolution of the current profile along the undulator, enabling better interpretation of the other fields in "/Beam/...".
2) Global statistics of energy spread + mean energy: If requested by setting the new flag beam_global_stat=true in &setup block (default value is false, i.e. OFF), the energy spread (and mean energy) of the entire beam are reported as datasets "/Beam/Global/energy" and "/Beam/Global/energyspread" for every integration step. Documentation in manual will follow.

additional output in .out.h5 (branch cl_20210313__globalstats)

---

include/LatticeElements.h
include/Sequence.h
src/Core/Control.cpp
src/Core/Field.cpp
src/Loading/QuietLoading.cpp
src/Main/AlterSetup.cpp
src/Main/GenMain.cpp

These changes fix various memory leaks. In particular, the memory holding the fields of the harmonics discarded during harmonic upconversion is properly released. Note that possible memory loss that might occur during subharmonic conversion (also here the discarded fields) was not fixed, yet.

various fixes of memory leaks

---

Makefile
build_info.sh
include/Track.h
src/Main/mainwrap.cpp

This fixes a couple of compiler & linker problems when getting started with Genesis.
- `build_info`: boundle into library
- avoids needing to care about link order (left-to-right)
- `build_info`: fix symbol error
- add declaration via include file
- `Makefile`: Fix Link Object Order
- The order of objects and libs in the linker line matters: from left-to-right, the next command will always fill in the
symbols marked as missing on the left. This fixes various linker errors.
- `Track.h`: mpi & hdf5 are "system"
- External "system"-provided (or package manager provided) libs should be included with `<>` to avoid include/compiler errors.
- `mainwrap`: missing includes & namespace
- Fix compile errors:
- missing stdlib includes that are used
- missing implied `std` namespace use

Fix Compile & Linker 

---

include/build_info.h

'extern "C"' is now only visible to C++ compilers, fixing compilation
issues with updated Makefile.
Tested on Ubuntu 16.04LTS and CentOS 7.9.2009 Core (using gcc v8).

fix compiler error caused by build_info.h

---

src/IO/Output.cpp

Also handle possible errors during user name look-up for field
/Meta/User, as they would crash the simulation (getpwuid() would
return NULL pointer).

store number of MPI processes in .out.h5 as /Meta/mpisize

---

include/Collective.h
include/Control.h
include/Gencore.h
include/HDF5base.h
include/Output.h
include/Profile.h
include/SDDSBeam.h
include/Series.h
include/Sorting.h
include/Undulator.h
include/genesis.h
include/readBeamHDF5.h
include/readFieldHDF5.h
include/writeBeamHDF5.h
include/writeFieldHDF5.h
include/writebeam.h
src/Main/GenMain.cpp

Use the correct "external" includes to make builds more robust:
- `<mpi.h>`
- `<hdf5.h>`

mpi/hdf5.h includes: <>

---

src/Main/mainwrap.cpp

If the shotnoise seed is neither explicitly assigned in &setup nor
set by using the "-s" command line option, an undefined seed value
was used (uninitialized variable). This patch fixes this issue, the
seed defaults then to the value described in the manual (&setup section).

fixed potentially uninitialized value of shotnoise seed

---

include/writeFieldHDF5.h
src/IO/writeFieldHDF5.cpp

Still to be done:
. determine reasonable scaling factors for matrix elements (currently data should be considered to be in arb. units)
. current dimension matrix dimension of /int_xz and /int_yz is "ngrid x nslices". Think if these matrices should actually be written to .fld.h5 file in transposed data orientation

patch to write projections into .fld.h5 file

---

src/Core/Undulator.cpp
src/Lattice/Lattice.cpp

Fixes compilation error with older gcc version 4.8.5 when using compiler settings "-O2" or "-O0 -g" (= not requesting specific version of C++ standard).

fix two minor compilation issues

---

CHANGELOG.md
CMakeLists.txt
MANUAL_MAIN.md
include/Parser.h
include/SemaFile.h
include/Setup.h
include/genesis.h
src/Main/GenMain.cpp
src/Main/Parser.cpp
src/Main/Setup.cpp
src/Main/mainwrap.cpp
src/Util/SemaFile.cpp

* Added new parser for command line options
* Added semaphore file functionality:
- Can be controlled either by two new options in &setup or by specifying name using new command line option --semaphore-file (then there is no need to modify the input file)
- File is generated only after successful simulation run
* Exit code of G4 binary now depends on simulation status: returns 0 if successful, 1 in case of error

semaphore files + new command line parser

---

CHANGELOG.md
CMakeLists.txt
include/FieldSolver.h
include/HDF5_cwc.h
include/Track.h
src/Core/FieldSolver.cpp
src/IO/HDF5_cwc.cpp
src/Main/Track.cpp

Dumping of 'crsource' is enabled by setting the currently undocumented parameter 'dbg_dump_crsource' to true and dbg_dump_crsource_step controls how often the file is generated (in number of integration steps, the default value is 100).
If filter_diff is 'false', these settings have no effect (because the source term filtering is then inactive).
Warning: The generated files are very large (larger than a complete field dump).
This is the structure of the generated HDF5 files (example for a simulation with ngrid=315):
```
% h5ls -r test.1000.crsource.h5
/                        Group
/crsource                Dataset {36864, 99225, 2}
/crsource_filtered       Dataset {36864, 99225, 2}
/filter                  Dataset {99225}
```

Code to write out the 'crsource' before and after filtering.

---

CHANGELOG.md
CMakeLists.txt
include/FieldManipulator.h
src/Main/FieldManipulator.cpp
src/Main/GenMain.cpp

Adds 'field_manipulator' namelist.
Currently only scaling of power of the light field is supported, but I plan to implement some additional features in the future.
Example:
```
&field_manipulator
harm = 1
scale_power = 0.1
&end
```
==> Power of field in fundamental is attenuated by one order of magnitude. By putting multiple of these blocks, different harmonics can be scaled by different factors (for instance for harmonic lasing studies).
The manipulation is done in memory, avoiding time-intensive file-based field manipulation, which uses the steps: (i) dumping of fields to files, (ii) manipulation of the files, and (iii) loading fields into GENESIS again to continue with the simulation.
During the merge, CHANGELOG.md will generate a conflict that has to be manually resolved (order of the …

namelist 'field_manipulator'

---

include/Diagnostic.h
src/Core/Diagnostic.cpp

Running with fields having different 'ngrid' causes crashes, either with SIGSEGV in Diagnostic code or a crash due to heap issues at a later time. For instance if the first field (h=1) has ngrid=51 and the second field (for example h=3) has ngrid=201.
This patch fixes these issues by adding code to manage separate FFTW resources (plan, in/out buffers) for all ngrid values.

Fix crash in Diagnostic code when using fields having different 'ngrid'

---

include/Sorting.h
src/Util/Sorting.cpp

Handle integer overflow situations that can happen during sorting for simulations with high beam current (several kA), long wavelengths (several micro-meters), and strong chicanes.
While our current simulation parameters still have some margin to these problematic conditions, it is preferrable to stop with a user-friendly error message. If everything went well, at the end of the global sorting process the maximum seen transfer size is reported.
These changes implement a user-friendly error message, for example:
`Sorting::send (on rank 33): Number of data in send buffer is 2176251030, exceeding maximum MPI transfer size of INT_MAX (too many particles to be moved to neighboring rank), exiting.`
Before, the symptoms of integer overflow were for instance:
```
[max-exfl194:192212] *** An error …
```

Improve handling of error conditions in class Sorting

---

src/Core/Undulator.cpp

Display also 0% progress of actual simulation.
This makes the program more user-friendly because it is clear that the simulation is now running (and large simulations might need hours until 10% progress is reached which used to be the first progress message).
Example output:
```
Running Core Simulation...
Time-dependent run with 7296 slices for a time window of 1.0051 microns
Initial analysis of electron beam and radiation field...
Calculation: 0% done
Calculation: 10% done
Calculation: 20% done
[..]
```

display also simulation progress of 0%

---

src/Util/GaussHermite.cpp

`yangle` parameter in `&field` had no effect, `xangle` was introducing angle in x and y plane

 bugfix in field initialization code (xangle/yangle parameters)

---

include/FieldManipulator.h
src/Main/FieldManipulator.cpp
src/Main/GenMain.cpp

Spiral phase plate (SPP) introduces phase shift of electric field, depending on transverse position.
Parameters: `spp_l`, `spp_phi0`, `spp_nsect`. Specifying any of these parameters activates the SPP code block.
Added new namelist `&alter_field` that will eventually replace `&field_manipulator`. As of now, `&field_manipulator` can still be used and the message
```Warning: &field_manipulator is deprecated and will be removed in the future. Use &alter_field instead.```
is displayed.

field_manipulator: add support for SPPs

---

include/writeBeamHDF5.h
include/writeFieldHDF5.h
src/IO/writeBeamHDF5.cpp
src/IO/writeFieldHDF5.cpp
src/Main/Dump.cpp

If the file cannot be created the field/beam dump operation aborts. This catches already lots of issues, however, IO errors after opening the file for write still require additional handling.

some error handling for field/beam dumping

---

include/Control.h
include/Diagnostic.h
include/DiagnosticHook.h
include/Gencore.h
include/Output.h
include/Setup.h
include/Undulator.h
src/Core/Control.cpp
src/Core/Diagnostic.cpp
src/Core/DiagnosticHook.cpp
src/Core/DiagnosticHookBeam.cpp
src/Core/DiagnosticHookLI.cpp
src/Core/Gencore.cpp
src/IO/Output.cpp
src/IO/readBeamHDF5.cpp
src/Lattice/Lattice.cpp
src/Main/GenMain.cpp
src/Main/Setup.cpp
src/Main/Track.cpp

- More I/O error handling (now also for .out.h5 file)
- Report names of main input file and lattice file while processing them
- Added option to write copy of simulation metadata also to small, independent file. Then the metadata (version information etc.) can be preserved when removing the .out.h5 file. Controlled by new parameter `write_meta_file` in `&setup`.
- Enforce loading of correct plugin type. So far a field plugin .so file could be loaded as plugin for beam  diagnostics, which resulted in a crash. Now an error msg is displayed.
- Store `info_txt` field provided by plugins into metadata in `.out.h5` file. This user defined string can for instance contain the git commit ID of the source that was used to build the module.
- Debug option to skip writing of .out.h5 file (set …

various small enhancements

---

src/Lattice/LatticeParser.cpp

This patch adds code to enforce unique element labels in lattices.
In this code, redefinition of an element label is considered an error. If needed, one could change this to a milder reaction. But a warning should be displayed in any case (this could help to debug simulation issues related to duplicate element labels).

 enforce unique element labels in lattices

---

src/Main/mainwrap.cpp

Change exit code to 1 in case of illegal arguments or missing input filename.
So far the exit code in these cases was 0, so SLURM was incorrectly reporting "success".

exit code=1 in case of illegal arguments or missing input filename

---

src/Main/Wake.cpp

Building Genesis4 clued me into a bug in the master branch, a memory leak of 3 arrays in `Wake.cpp` post-`init()`:
```
2023-12-04T23:03:48.8335470Z /Users/runner/Miniforge3/conda-bld/genesis4_1701730808588/work/src/Main/Wake.cpp:120:20: warning: left operand of comma operator has no effect [-Wunused-value]
2023-12-04T23:03:48.8434770Z   delete[] wakeres,wakegeo,wakerou,wakeext;
2023-12-04T23:03:48.8535100Z                    ^~~~~~~
2023-12-04T23:03:48.8592490Z /Users/runner/Miniforge3/conda-bld/genesis4_1701730808588/work/src/Main/Wake.cpp:120:28: warning: left operand of comma operator has no effect [-Wunused-value]
2023-12-04T23:03:48.8695580Z   delete[] wakeres,wakegeo,wakerou,wakeext;
2023-12-04T23:03:48.8743960Z                            ^~~~~~~
2023-12-04T23:03:48.8843570Z …
```

Fix memory leak of wakegeo, wakerou and wakeext

---

CHANGELOG.md
CHANGELOG_DEV.md
include/SimpleHandshake.h
manual/MAIN_INPUT.md
src/Main/GenMain.cpp
src/Util/SimpleHandshake.cpp

Now the default is that waiting GENESIS processes do not burn CPU time. The processors can be used for other tasks. The names of the files used for the synchronization can now be adjusted using the parameter "file". Documentation was added.
Additionally, created new, separate CHANGELOG_DEV.md to collect changes during the development process. During the release process, these changes would be moved over to the "main" CHANGELOG.md.

improve waiting in simple_handshake block

---

src/IO/readFieldHDF5.cpp

In case of incorrect filename, one got so far the misleading message "Error: Mismatch between reference length of run and of input file" (from `readFieldHDF5.cpp`)

importfield: handle issues with non-existent .fld.h5 file

---

.github/workflows/gh-pages.yml
manual/MAIN_INPUT.md
src/Loading/Series.cpp
src/Loading/SeriesParser.cpp
src/Main/EField.cpp

* Fix the documentation deployment - it should only happen for your (@svenreiche) repository on the master branch or a tagged release
* Fixed some `usage` methods which had either incorrect namelist names or parameter information
* Added missing parameters from browsing the source code to the namelists
* Added missing namelists found from the source code into an "unsupported namelists" section in the manual
* There are a bunch of "TODOs" there as I'm not knowledgeable enough to fill them in myself.
* If you agree that they could go in the manual, feel free to either suggest fixes in this PR (or however you prefer)

Fix usage of some namelists and the associated documentation

---

include/ImportField.h
src/Loading/ImportField.cpp

This patch adds the new, experimental feature to replace already existing fields with a field imported from a file.
The new parameter `replace` was added to `importfield` and the default behavior remains unchanged.
If the user provides `replace=true` to `&importfield`, then an already existing field at this harmonic will be replaced by the data loaded from the field file.

importfield: Possibility to replace already existing fields

---

include/Collective.h
src/Core/Collective.cpp

As a first step to fix the memory corruption issues reported in bug report https://github.com/svenreiche/Genesis-1.3-Version4/issues/144 , the data arrays were replaced by std::vector. Many (but not all) data accesses are done via `at()`, avoiding that indexing issues go undetected in the future.
As a second step, if possible, the code block should be reworked to use integer arithmetic (and avoid floating point arithmetic) as much as possible to avoid the rounding issues reported in https://github.com/svenreiche/Genesis-1.3-Version4/issues/144 . 
Moreover, since the computation of the parameters done in function `Wake::init` uses several parameters from an instance of class `Time`, it might be useful to pass a const pointer to that instance to `Collective::initWake` instead of these …

conversion of data storage in class Collective to std::vector

---

CHANGELOG_DEV.md
include/Collective.h
src/Core/Collective.cpp

In every MPI process, only report first two interventions. The user is informed about the activity of the workaround, but stdout logfiles are no longer filled with lots of repeating messages.

make workaround in Collective.cpp less verbose

---

include/HDF5base.h
include/Output.h
src/IO/HDF5base.cpp
src/IO/Output.cpp
src/Main/mainwrap.cpp

To include the git commit id of the source code into the compiled binary, the build process uses the header file "version.h", that is generated every time `make` is ran. So far this header file was in turn included by other header files, resulting in many dependencies from a file changing during every time a build is done.
This patch removes the includes from other header files and "version.h" is instead included directly where it is needed.
Test case (run it in your build directory):
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
make
```
With the source files in commit id 4681421b (date: 2024-03-20), invoking `make` a second time (without changing any source file) results in the compilation of 41 cpp source files (takes a bit above a minute in my development environment).
With the changes …

reorganize #include "version.h"

---

CMakeLists.txt
misc/plugin_testbench/CMakeLists.txt
misc/plugin_testbench/README.md
misc/plugin_testbench/demo_params.txt
misc/plugin_testbench/g4_tb.cpp
misc/plugin_testbench/g4_tb_util.cpp
misc/plugin_testbench/g4_tb_util.h

This test environment for diagnostic plugins (currently only for field analysis) can be used to debug (and also benchmark) the code in diagnostics plugins without having to run a full "GENESIS 1.3" simulation.
Currently, the following steps are performed:
- load diagnostic plugin, as specified by user
- generate Gaussian light field, only with transverse dependency. In the moment loading from `.fld.h5` files is NOT supported (yet)
- call diagnostic plugin with the field data
- write the collected results to a `.txt` file, with formatting suitable for Python (`numpy.array`)
MPI is supported, meaning that you can run the program for instance with `mpirun`. In this case the `.txt` file contains the data collected from all processes.
As described in the README.md file that comes with the …

test environment for diagnostic plugins

---

include/Setup.h
src/Main/Setup.cpp

If the user provides the `outputdir` parameter in `&setup`, now a zero-byte temporary file is generated (and then deleted) in the directory.
This test ensures that the output directory exists and is writable. The simulation stops at the `&setup` block should this test fail. So far, the simulation would proceed with the numerically expensive tracking and only crash when about to generate the first output file.

check if output directory exists and is writable

---

include/SeriesManager.h
src/Lattice/LatticeParser.cpp
src/Loading/SeriesManager.cpp

- Warns if sequence is to be replaced by sequence with same (case-sensitive) name
- Warns if sequence name contains any upper-case characters, as these can lead to issues with lattices. For instance if an undulator definition in the lattice file contains `aw = @AW`, a look-up for sequence named "aw" will be done. (So in the process of lattice parsing the letters are converted to lower-case.)

add warnings related to sequences

---

include/genesis.h
src/Main/GenMain.cpp
src/Main/mainwrap.cpp

Reason: Syscall `clock()` gives the CPU time spent by the process, not the wall clock time. For example, if your process is sleep()-ing for a longer time, this time is not included (as one would expect for a wall clock time display).
Therefore temporarily disabled the output until this is fixed.

for now, disable display of "wall clock time" at end of the program execution

---

src/Main/mainwrap.cpp

The combination of all merged pull requests resulted in status of `dev` branch that did not compile.
The reason is a missing include of `hdf5.h`, this patch fixes it.

minor: fix missing include hdf5.h

---

src/Loading/SeriesParser.cpp
src/Main/mainwrap.cpp

Just small stuff.
- added info comment: location of class implementations
- debug command line argument `--dbg-versions` now explicitly states if binary was compiled w/o FFTW3

small additions

---

src/IO/Output.cpp
src/IO/readBeamHDF5.cpp

Fixes compiler message reporting potential buffer overflow (reported for example by gcc version `gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`).
In total two char array lengths were adjusted to address warnings such as:
```
/home/cl/g4/x/Genesis-1.3-Version4/src/IO/readBeamHDF5.cpp:152:27: warning: ‘/theta’ directive writing 6 bytes into a region of size between 4 and 9 [-Wformat-overflow=]
152 |   sprintf(name,"slice%6.6d/theta",islice);
|                           ^~~~~~
In file included from /usr/include/stdio.h:894,
from /usr/include/c++/11/cstdio:42,
from /usr/include/c++/11/ext/string_conversions.h:43,
from /usr/include/c++/11/bits/basic_string.h:6608,
from /usr/include/c++/11/string:55,
from /usr/include/c++/11/bits/locale_classes.h:40,
from /usr/include/c++/11/bits/ios_base.h:41, …
```

fix compiler warnings related to array lengths

---

manual/MAIN_INPUT.md
src/IO/SDDSBeam.cpp

`&import_distribution` `settimewindow` is by default false in the codebase, but is noted as default true in the documentation.
Context: for https://github.com/slaclab/lume-genesis/ it's important we have these defaults correct so that the Python classes will be generated appropriately.
A quick check, after the changes in this PR:
```c
$ git grep settime
include/SDDSBeam.h:   bool center,match,settime;
manual/MAIN_INPUT.md:- `settimewindow` (*bool, false*): set time window.
src/IO/SDDSBeam.cpp:  settime=false;
src/IO/SDDSBeam.cpp:  cout << " bool settimewindow = false" << endl;
src/IO/SDDSBeam.cpp:  if (arg->find("settimewindow")!=end)   {settime= atob(arg->at("settimewindow").c_str());arg->erase(arg->find("settimewindow"));}
src/IO/SDDSBeam.cpp:  if (settime){
```
(cc @balticfish)

DOC: import_distribution settimewindow is by default false

---

examples/Example3-TimeDependent/README.md

I believe this is a typo.
Also, as a newcomer, I have a hard time understanding the whole paragraph and the following.
E.g.: "The given example requests an integration step size of 45 mm, which corresponds to three undulator periods. This means that after one single integration step the field is pushed three wavelength." Why is the field pushed 3 wavelengths and not 3 undulator periods? (Sorry, I don't see the connection of the argument with delz.)
Is there a rule of thumb on how to choose 'delz' and 'sampel'?

Example3 readme

---

include/ImportField.h
include/readFieldHDF5.h
manual/MAIN_INPUT.md
src/IO/readFieldHDF5.cpp
src/Loading/ImportField.cpp

I implemented an attenuation factor for the field import element. This allows for importing and scaling field files without the need of modifying or creating copies of large hdf5 files.
The manual has also been updated to reflect the change.

Import field attenuation

---

include/LatticeParser.h
src/Lattice/LatticeParser.cpp

This is useful for simulating continuous inter-undulator slippage, such as the prime sequence slippage of HB-SASE

Add support of sequence using in definition of chicane delay

---

.github/genesis4-build-env-mpich.yaml
.github/genesis4-build-env-openmpi.yaml
.github/scripts/build.sh
.github/scripts/run_tests.sh
.github/workflows/build.yaml
.github/workflows/conda-build.yml
CMakeLists.txt

This PR adds GitHub Actions building of `genesis4` with both system-level and Conda-based builds across Linux/MacOS and OpenMPI/MPICH.
There are also a couple tweaks to the `CMakeLists.txt` to avoid overwriting the environment CXXFLAGS (instead using CMake features to explicitly link `stdc++`).
* `.github/workflows/build.yaml` definse a GitHub Actions workflow for system-level builds and tests, supporting Ubuntu and macOS with OpenMPI and MPICH.
* `.github/workflows/conda-build.yml` defines a GitHub Actions workflow for Conda-based builds and tests, supporting Ubuntu and macOS with OpenMPI and MPICH.
* `.github/scripts/build.sh` - a shared build script for conda/system libraries.
*  `.github/scripts/run_tests.sh` performs basic validation of the built Genesis4 binary by checking its …

CI: build Genesis4 on GitHub Actions (system libraries, conda)

---

src/Main/GenMain.cpp

So far exit code was 0 in case of non-existent main input file (code 0 signals everything is ok) ...

Fix incorrect exit code 0 for non-existent main input file

---

src/Main/Wake.cpp

This is a drop-in replacement for Wake::singleWakeResistive that reproduces SLAC-PUB-10707 wakefields.
Developed with the help of ChatGPT o3.
This addresses https://github.com/svenreiche/Genesis-1.3-Version4/issues/231. With those parameters, the integrated Wakefield looks like:
with `-70 keV` average energy change
The code includes a block that writes `Wz.txt` for debugging. This shows excellent  agreement with the LCLS case in SLAC-PUB-10707. Complete code:
```python
import numpy as np
from scipy.constants import epsilon_0, e
import matplotlib.pyplot as plt
GEOMETRY = 'flat'
z, Wz = np.loadtxt(f'Wz_{GEOMETRY}.txt').T
if GEOMETRY == 'round':
file = "SLAC-PUB-10707-digitized-Fig4-AC-Cu.csv"
elif GEOMETRY == 'flat':
file = "SLAC-PUB-10707-digitized-Fig8-AC-Cu.csv"
raw_data = …
```

Fix singleWakeResistive to reproduce SLAC-PUB-10707 wakefields.

---

src/Main/Wake.cpp

This removes the debug print to file of the resistive wall wake. The user can get the same data now with `output=` in the wake definition.

Remove debug print
